language: python
python:
    - "3.5"
services:
    - mongodb
before_script:
    - sleep 15
    - mongo mydb_test --eval 'use separationsheets; db.createCollection("sheets");'
install: 
    - "pip install -r requirements.txt"
    - "pip install -r requirements_dev.txt"
    - "python setup.py install"
script: 
    - coverage run --source separationsheet_site -m py.test 
    - flake8 --exit-zero
after_success:
    - coverage report
    - coveralls
